baseURL: https://theguillemetsproject.com
languageCode: en-us
title: The Guillemets Project
theme: "PaperMod"
publishDir: "docs"
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: about
          name: about
          url: /about/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        # - identifier: podcast
        #   name: podcast
        #   url: /podcast/
        #   weight: 30
        - identifier: voices
          name: voices
          url: /voices/
          weight: 40

params:
    homeInfoParams:
        Title: Welcome, Bienvenue! 
        Content: The Guillemets Project is a podcast by Spyridon Simotas and Alexis Osipovs at the University of Virginia.

    socialIcons: # optional
        - name: "<spotify>"
          url: "<link>"
        - name: "<platform 2>"
          url: "<link2>"
